project:
  type: website

website:
  title: "infoblog"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: docked
    contents:
      - href: myself.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

